#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

device:
  base: firefox
  compare: firefox

#If you want to have multiple snapping files, set the file name here
# snap_file: "lib/wraith/javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'public/screenshots/ca-wiki'

# Add only 2 domains, key will act as a label
domains:
  wiki-dev: "http://wiki-dev.ca.com"
  wiki: "http://wiki.ca.com/xxxxx"

#Type screen widths below, here are a couple of examples
screen_widths:
# - 320
#  - 600
  - 768
  - 1024
  - 1280

## TODO: get in various locales somehow & call the browser using each one of them.
locales:
  - en
  - fr
  - de
  - it
  - pt_BR


#Type page URL paths below, here are a couple of examples
paths:
  home: /
#  uk_index: /uk

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10


#WraithDaemon
wraith_daemon:
  report_location: "http://localhost:4567"
  notifications:
    enabled: true
    smtp_host: ""
    from: ""
    to: ""
    subject: ""
